/*global $*/

$(function(){
   
    $("#hoverback1").hover(function(){
        $("#back1").css({
            "width":"100%",
            "height":"100%"
        });
        $(this).css("transform","scale(1.1,1.1)");
        $("#p1").css("color","#fff");
    },function(){
        $("#back1").css({
            "width":"0%",
            "height":"0%"
        });
        $(this).css("transform","scale(1,1)");
        $("#p1").css("color","#000000");
    });
    $("#hoverback2").hover(function(){
        $("#back2").css({
            "width":"100%",
            "height":"100%"
        });
        $(this).css("transform","scale(1.1,1.1)");
        $("#p2").css("color","#fff");
    },function(){
        $("#back2").css({
            "width":"0%",
            "height":"0%"
        });
        $(this).css("transform","scale(1,1)");
        $("#p2").css("color","#000000");
    });
    $("#hoverback3").hover(function(){
        $("#back3").css({
            "width":"100%",
            "height":"100%"
        });
        $(this).css("transform","scale(1.1,1.1)");
        $("#p3").css("color","#fff");
    },function(){
        $("#back3").css({
            "width":"0%",
            "height":"0%"
        });
        $(this).css("transform","scale(1,1)");
        $("#p3").css("color","#000000");
    });
    $("#hoverback4").hover(function(){
        $("#back4").css({
            "width":"100%",
            "height":"100%"
        });
        $(this).css("transform","scale(1.1,1.1)");
        $("#p4").css("color","#fff");
    },function(){
        $("#back4").css({
            "width":"0%",
            "height":"0%"
        });
        $(this).css("transform","scale(1,1)");
        $("#p4").css("color","#000000");
    });
    $("#hoverback5").hover(function(){
        $("#back5").css({
            "width":"100%",
            "height":"100%"
        });
        $(this).css("transform","scale(1.1,1.1)");
        $("#p5").css("color","#fff");
    },function(){
        $("#back5").css({
            "width":"0%",
            "height":"0%"
        });
        $(this).css("transform","scale(1,1)");
        $("#p5").css("color","#000000");
    });
    $("#p1").slideToggle(300,function(){
        $("#p2").slideToggle(300,function(){
            $("#p3").slideToggle(300,function(){
                $("#p4").slideToggle(300,function(){
                  $("#p5").slideToggle(300)
                });
            });
        }); 
    });
});
