/*global $*/

$(function(){
  $("#a1").fadeToggle(500);
    
    $("#b1").hover(function(){
      $(this).css("background-color","#ba4343");
    },function(){
      $(this).css("background-color","#efefef");
    });
     $("#b2").hover(function(){
      $(this).css("background-color","#ba4343");
    },function(){
      $(this).css("background-color","#efefef");
    });
     $("#b3").hover(function(){
      $(this).css("background-color","#ba4343");
    },function(){
      $(this).css("background-color","#efefef");
    });
     $("#b4").hover(function(){
      $(this).css("background-color","#ba4343");
    },function(){
      $(this).css("background-color","#efefef");
    });
     $("#b5").hover(function(){
      $(this).css("background-color","#ba4343");
    },function(){
      $(this).css("background-color","#efefef");
    });
     $("#b6").hover(function(){
      $(this).css("background-color","#ba4343");
    },function(){
      $(this).css("background-color","#efefef");
    });
     $("#b7").hover(function(){
      $(this).css("background-color","#ba4343");
    },function(){
      $(this).css("background-color","#efefef");
    });
     $("#b8").hover(function(){
      $(this).css("background-color","#ba4343");
    },function(){
      $(this).css("background-color","#efefef");
    });
     $("#b9").hover(function(){
      $(this).css("background-color","#ba4343");
    },function(){
      $(this).css("background-color","#efefef");
    });
     $("#b10").hover(function(){
      $(this).css("background-color","#ba4343");
    },function(){
      $(this).css("background-color","#efefef");
    });    
});
